module com.kobi401.browser {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;

    requires org.controlsfx.controls;
    requires com.dlsc.formsfx;
    requires net.synedra.validatorfx;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.bootstrapfx.core;
    requires eu.hansolo.tilesfx;
    requires com.almasb.fxgl.all;
    requires jdk.jsobject;
    requires java.logging;
    requires jdk.management;
    requires java.desktop;

    opens com.kobi401.browser to javafx.fxml;
    exports com.kobi401.browser;
    exports com.kobi401.browser.download.downloadManager;
    opens com.kobi401.browser.download.downloadManager to javafx.fxml;
    //exports com.kobi401.browser.ui.;
    //opens com.kobi401.browser.ui. to javafx.fxml;
    exports com.kobi401.browser.memory.tabs;
    opens com.kobi401.browser.memory.tabs to javafx.fxml;
    exports com.kobi401.browser.engine.main;
    opens com.kobi401.browser.engine.main to javafx.fxml;
    exports com.kobi401.browser.ui.about;
    opens com.kobi401.browser.ui.about to javafx.fxml;
    exports com.kobi401.browser.ui.bookmark;
    opens com.kobi401.browser.ui.bookmark to javafx.fxml;
    exports com.kobi401.browser.ui.menubar;
    opens com.kobi401.browser.ui.menubar to javafx.fxml;
    exports com.kobi401.browser.ui.navigationbar;
    opens com.kobi401.browser.ui.navigationbar to javafx.fxml;
    exports com.kobi401.browser.ui.GUI;
    opens com.kobi401.browser.ui.GUI to javafx.fxml;
    exports com.kobi401.browser.ui.TextField;
    opens com.kobi401.browser.ui.TextField to javafx.fxml;
    exports com.kobi401.browser.ui.settings;
    opens com.kobi401.browser.ui.settings to javafx.fxml;
    exports com.kobi401.browser.ui.splash;
    opens com.kobi401.browser.ui.splash to javafx.fxml;
    exports com.kobi401.browser.ui.themes;
    opens com.kobi401.browser.ui.themes to javafx.fxml;
    exports com.kobi401.browser.download.ui;
    opens com.kobi401.browser.download.ui to javafx.fxml;
    exports com.kobi401.browser.download.downloadTask;
    opens com.kobi401.browser.download.downloadTask to javafx.fxml;
}